#!/usr/bin/env bash

#      LOG_TEMP_DIR: install-logs
#      DRONE_SERVER:  ${DRONE_SERVER}
#      GITHUB_AUTOMATION_API_KEY:  ${GITHUB_AUTOMATION_API_KEY}
#      DRONE_TOKEN:  ${DRONE_TOKEN}
#      GS_PROJECT_ID: ${GS_PROJECT_ID}
#      GS_CLIENT_EMAIL: ${GS_CLIENT_EMAIL}
#      GS_PRIVATE_KEY: ${GS_PRIVATE_KEY}

export TEST_BUILD_IMAGE=""
export TEST_URL_ARRAY=(${ESX_HOST_0} ${ESX_HOST_1} ${ESX_HOST_2} ${ESX_HOST_3})
export TEST_RESOURCE=/${DATACENTER_NAME}/host/${CLUSTER_NAME}
export TEST_TIMEOUT=60s
export VIC_ESX_TEST_DATASTORE=/${DATACENTER_NAME}/datastore/${DATASTORE_NAME}
export VIC_ESX_TEST_URL=${ESX_USERNAME}:${ESX_PASSWORD}@${ESX_URL}

export BIN=$GOPATH/src/github.com/vmware/vic/bin
export GOPATH=$GOPATH
export SHELL=/bin/bash

export TEST_USERNAME=${ESX_USERNAME}
export TEST_PASSWORD=${ESX_PASSWORD}
export TEST_DATASTORE=${DATASTORE_NAME}
export TEST_RESOURCE=${CLUSTER_NAME}
export TEST_TIMEOUT=60s

export GOVC_USERNAME=${ESX_USERNAME}
export GOVC_PASSWORD=${ESX_PASSWORD}
export GOVC_DATACENTER=${DATACENTER_NAME}
export GOVC_DATASTORE=${DATASTORE_NAME}
export GOVC_RESOURCE_POOL=${CLUSTER_NAME}
export GOVC_HOST=${ESX_URL}
export GOVC_INSECURE=true

export BRIDGE_NETWORK=${BRIDGE_NETWORK}
export PUBLIC_NETWORK=${PUBLIC_NETWORK}
export DOMAIN=${ESX_TLS_CNAME}
export REGISTRY_PASSWORD=${REGISTRY_PASSWORD}

pybot --removekeywords TAG:secret --exclude skip tests/test-cases